language: php

php:
- '5.6'
- '7.1'
- '7.2'
- nightly

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install: composer self-update

install: composer install --dev --prefer-dist --no-interaction

script:
  - make app-test-with-code-coverage
  - make app-cs-check
  - make app-security-check
